# Use postgres/example user/password credentials
version: '3.7'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data
  todo:
    depends_on:
      - database
    build: ./server
    ports:
      - 80:3000
    volumes:
      - ./server:/opt/todo
  test:
    build:
      context: ./server
      dockerfile: Dockerfile_test
    volumes:
      - ./server:/opt/todo

volumes:
  db_volume:
